name: Discovery CI

concurrency:
  group: discovery:${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "develop" ]
    paths: [ "feed_resources/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          cd feed_resources
          chmod +x ./gradlew
          ./gradlew build
