name: Jetpack Compose CI

concurrency:
  group: compose:${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "compose/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          cd compose
          chmod +x ./gradlew
          ./gradlew build
